FROM continuumio/miniconda3

ENV DB_DATABASE ""
ENV DB_USERNAME ""
ENV DB_PASSWORD ""
ENV DB_HOST ""
ENV DB_PORT 3306
ENV DB_DRIVERNAME "mysql+pymysql"

COPY requirements.txt /app/
COPY reader.py /app/
COPY config.py /app/
WORKDIR /app

RUN pip install -r requirements.txt

ENTRYPOINT ["python"]

CMD ["reader.py"]